title: Precision Audioworks
description: "From home audio to commercial AV and event sound, Precision Audioworks delivers expertly designed and installed audio solutions for every environment."
baseurl: ""
url: "https://precisionaudioworks.com.au"
language: en
region: AU

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - LICENSE
  - node_modules/
  - purgecss.config.js
  - Rakefile
  - README.md
  - vendor/